//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tarea6A
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Avales()
        {
            this.Avalan = new HashSet<Avalan>();
        }
    
        public int IdAval { get; set; }
        public string Nombre { get; set; }
        public string Domicilio { get; set; }
        public string Teléfono { get; set; }
        public string NoEscritura { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Avalan> Avalan { get; set; }
    }
}
