//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tarea6A
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagos
    {
        public int Folio { get; set; }
        public int IdP { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> MontoPago { get; set; }
    
        public virtual Préstamos Préstamos { get; set; }
    }
}
