//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tarea6A
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trabajan
    {
        public string Rfc { get; set; }
        public int IdEmp { get; set; }
        public Nullable<System.DateTime> FechaIni { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Empresas Empresas { get; set; }
    }
}
